repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2  # Match the version in your uv.lock
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # Match the version in your uv.lock
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: debug-statements
